### ISSUE TITLE
Cloudfare has depreciated the __cfduid cookie. Will that mess things up?

### ISSUE THREAD

**Issue by codytime** [acabey/JBLearning-Flashcard-Scraper#1]
https://blog.cloudflare.com/deprecating-cfduid-cookie/
I also do not see the __cfduid cookie on firefox. Any tips?

**Comment by acabey** [comment]
As that cookie is not related to authentication with the JBL service, more than likely you can simply remove it from the cookie dict without any effect on functionality

**Comment by codytime** [comment]
Oh, cool. thanks. I also could not locate the "ASP.NET_SessionId" value. any tips there?

**Comment by acabey** [comment]
Huh thats probably a bit more important. If you only include the values that are present does the script work? Sorry I can’t check on my own I haven’t touched this project in a while and I don’t have access to any JBL courses anymore

**Comment by codytime** [comment]
No worries, thanks a ton for helping out at all! Super handy tool. 
No, it produces the results files but they are blank.

**Comment by acabey** [comment]
I hate to abandon the project, but as I have no way to debug the code I really cannot update it to work with whatever changes JBL has made. If the "ASP.NET_SessionId" is missing, in the worst case that may mean they have completely changed frameworks, making the code in this project obsolete. If I find myself in a JBL course again, I will update, but until then I will just leave this up as a reference for anyone else motivated enough to give it a shot. At the end of the day its just a selenium scraping script :)
